### list all
GET http://localhost:3003/api/blogs HTTP/1.1
### get one
GET http://localhost:3003/api/blogs/67a7463aea14a48c2209eb92 HTTP/1.1
### delete one
DELETE http://localhost:3003/api/blogs/67aa19f6fff8e7489098a025 HTTP/1.1
### add one
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "TITLE - 3",
    "author": "AUTHOR - 3",
    "url": "URL/3"
}
### update
PUT  http://localhost:3003/api/blogs/??? HTTP/1.1
content-type: application/json

{
    "title": "TITLE - 3",
    "author": "AUTHOR - 3",
    "url": "URL/3"
}


### add
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "TITLE - 4",
    "author": "AUTHOR - 4",
    "url": "URL/4"
}
### delete
DELETE http://localhost:3003/api/blogs/67aa19d2fff8e7489098a020 HTTP/1.1
### update
PUT  http://localhost:3003/api/blogs/67aa1b9c71fb049fb57a1bb1 HTTP/1.1
content-type: application/json

{
    "title": "TITLE - y",
    "author": "AUTHOR - y"
}